### PR TITLE
Remove "PACKAGE_*" macro conflicts

### PR DESCRIPTION
**Pull request by qykth-git**
Remove `PACKAGE_*` macro conflicts from `src/gauche/config.h`.

### CODE REVIEW

**Comment by shirok** [comment]
Hmm.. this is the thing I don't like about autotools---they punish those who don't follow their way.

Let me think over it.  My hunch is that the right way is to use config.h only for compiling gauche source tree, and (if necessary) provide another header for extensions which only exposes the safe preprocessor symbols.

**Comment by qykth-git** [comment]
Those limitation comes from `autoheader(1)`. Because `autoheader(1)` can only handle one configuration header at once.

I rewrite patches and split header file into two (public and private) files.

**Comment by shirok** [comment]
I'm thinking more radical approach; do not expose preprocessor symbols without SCM_ prefix to the public, except the ones that are absolutely needed.  There are some that guards type declarations and #include headers, those we probably need to expose.

A possible option is to generate external config header that contains our own SCM_* symbols (e.g. SCM_HAVE_STDLIB_H).  We still want to reduce the number of those symbols to expose.

**Comment by shirok** [comment]
Finally, addressed this.

**Pull request closed without merging**
