### PR TITLE
line-edit: add M-d M-DEL M-< M-> and update C-a C-e

### PR DESCRIPTION
**Pull request by pclouds**
The four new keys are self explanatory (assuming you use Emacs). C-a and
C-e are remapped to the beginning and end of _line_ not buffer.

Not really optimized so unnecessary refresh may happen.

### CODE REVIEW

**Comment by shirok** [comment]
Great.  Thanks.

**Comment by lassik** [comment]
Great to see progress on a line editor!

**Comment by pclouds** [comment]
Here's a fun thing. How to implement M-(, which inserts `()` then moves the cursor back at `(`? The fun thing is doing it without breaking undo functionality. This requires M-( to pass two results back to the main loop, the undo sequence and `'moved`.

Ideally I think if we could refactor the input loop to accept a series of keystrokes from "elsewhere", then we have "editor macros" and can implement M-( as basically a sequence of `#\(`, `#\)` and `(ctrl #\b)` and not worried about anything.

It sounds good to me, but I have problem actually doing it. Maybe stick a queue of keystrokes in ctx, keep executing those until empty, then go back to getch?

**Comment by lassik** [comment]
> Ideally I think if we could refactor the input loop to accept a series of keystrokes from "elsewhere", then we have "editor macros" and can implement M-( as basically a sequence of `#\(`, `#\)` and `(ctrl #\b)` and not worried about anything.

Replaying an algorithm (especially in reverse) is generally more error-prone than simply caching the results at each step of the previous run.

This may be a dumb suggestion, but since it's just a REPL instead of a full-blown text editor that needs to handle huge files, could the undo list simply be an `(input-string . cursor-position)` pair after each keystroke? You can limit the depth of the undo history by tossing old entries from the tail of the list.

**Pull request merged**
