### PR TITLE
Add sys-strsignal procedure

### PR DESCRIPTION
**Pull request by lassik**
Wraps strsignal() which was added to POSIX in 2017.

### CODE REVIEW

**Comment by lassik** [comment]
Note that this can return NULL on some systems, and

```
errno = 0;
strsignal();
if (errno == 0) // then there is no such signal
```

can be used to check for existence of signal. Should the implementation be modified to take these into account?

**Comment by lassik** [comment]
https://pubs.opengroup.org/onlinepubs/9699919799/functions/strsignal.html

**Comment by shirok** [comment]
It's relatively new, so I'd like to check its availability with configure (MinGW doesn't have it yet).  MT-safety is another concern, though, it's the same situation as strerror() and probably unavoidable.
NULL return value can be mapped to #f.  However, there's no guarantee what's returned with invalid signal number, so the errno check seems necessary.

**Comment by lassik** [comment]
> It's relatively new, so I'd like to check its availability with configure (MinGW doesn't have it yet).

Good idea.

> MT-safety is another concern, though, it's the same situation as strerror() and probably unavoidable.

Yes. There's `strerror_r()`, but no `strsignal_r()`. POSIX explicitly says `strsignal()` is unsafe with threads. It should probably be wrapped in a global lock. You could also omit `sys-strsignal` and retrieve all the signal numbers at once. POSIX has a function to get the max signal number.

> NULL return value can be mapped to #f. However, there's no guarantee what's returned with invalid signal number, so the errno check seems necessary.

Yes. At least OSX returns a generic string for all numbers.

**Comment by lassik** [comment]
BTW I found out that the errno check isn't reliable either. errno isn't always set on unknown signal.

**Comment by shirok** [comment]
Added `sys-strsignal` with `configure` check.  `NULL` return value is mapped to `#f`.  If `strsignal()` is not available, it always returns `#f` for now.  We may add some reasonable fallback if necessary.

**Pull request closed without merging**
