### PR TITLE
Make iform->sexpr ignore identifiers

### PR DESCRIPTION
**Pull request by wasao**
## Before
```scm
gosh> (macroexpand-all '(cut print <>))
(lambda (|#<identifier srfi-26#x.e82d20>.0|) (print |#<identifier srfi-26#x.e82d20>.0|))
gosh> (macroexpand-all '((cut print <>) 1))
(letrec ((|#<identifier srfi-26#x.e821c0>.0| '1)) (print |#<identifier srfi-26#x.e821c0>.0|))
```

## After
```scm
gosh> (macroexpand-all '(cut print <>))
(lambda (x) (print x))
gosh> (macroexpand-all '((cut print <>) 1))
(letrec ((x '1)) (print x))
```

### CODE REVIEW

**Comment by shirok** [comment]
The ".0" part is crucial and shouldn't be dropped, for it needs to distinguish same local name with different bindings.  So I'd like to have it as

    (lambda (x.0) (print x.0))

etc.

**Comment by wasao** [comment]
I misunderstood. How do you think about the next change?

**Comment by wasao** [comment]
```scm
gosh> (macroexpand-all '(cut print <>))
(lambda (x.0) (print x.0))
gosh> (macroexpand-all '((cut print <>) 1))
(letrec ((x.0 '1)) (print x.0))
```

**Comment by shirok** [comment]
Looks ok.  Let me test it locally before merge.  Thanks!

**Comment by shirok** [comment]
Works great.  Merged.  Thanks!

**Pull request closed without merging**
