### PR TITLE
Autoconf update

### PR DESCRIPTION
**Pull request by qykth-git**
These commits will update autoconf usage.

* Update autoconf macros.
* Use "autoreconf(1)" to generate files.
* Use canonical methods to add some special parameter to sub-configure script.
* Other minor cleanup.

If you have any questions, please ask me.

### CODE REVIEW

**Comment by shirok** [comment]
Thanks.  I think we need some tweaks before merging.

* The files under gc/ will be overwritten whenever I grab new versions of bdwgc, so the changes
there should be minimal.   I'd rather have them untouched even if their convention is dated.
Ideally, the changes should be done upstream and I just grab them.

* I like autoconf, but not automake much, for it tends to introduce version dependency; one
setup for a particular automake version tend not to work on another versions, and I don't
want to force developers to commit to the same automake versions.  Subsequently, I chose to
avoid dependency on automake as much as possible; e.g. I check in some files that can
be autogenerated, but may depend on developer's environment, including acocal.m4.
I want the repository in a way that you only need autoconf  to rebuild the stuff.
It's ok to update autogenerated files occasionally, to incorporate newer autoconf
macros.  So, if you find it's better to update them, generate them locally
and submit a patch including those autogenerated files.  As far as it can be used in
autoconf (I think we can safely assume 2.69, for it is pretty stable) I'll adopt it.

**Comment by pclouds** [comment]
Getting off topic a bit, but is there any chance the new gauche-based configure stuff can be used to build gauche itself? I suppose requiring gauche to build itself may be too much, unless we can build a minimal gauche without ./configure.. Maybe just the extension stuff.

**Comment by qykth-git** [comment]
OK. I rewrite patches as you like.

**Comment by shirok** [comment]
Hi pclouds, I'm thinking of gradually leaving away from autotools, but the absolute requirement
is that you have to be able to build gauche from release tarball without requiring gauche, which
excludes the option to use gauche itself ("Building subset of gauche first, then build full gauche"
would make cross-compiling a lot more complicated.
Then autotools is probably still the best mature option guaranteed to work on vast majority
of platforms, especially on the support of dynamic linking.

**Comment by qykth-git** [comment]
Rewrites are done.

* Remove `autoreconf(1)` usage
* Not touch `gc/` except `gc/configure.gnu` and its related hack.

**Comment by shirok** [comment]
Perfect.  Thanks a lot!

**Comment by shirok** [comment]
Hi @qykth-git,
gc/configure.gnu mechanism doesn't seem to handle out-of-tree build.  I'm not familiar with
this configure.gnu convention but do you know how it is typically handled?  Just want to
know the current practice before jumping onto duct-tape fix.

**Pull request merged**
