### PR TITLE
line-edit: persistent history with $GAUCHE_HISTFILE

### PR DESCRIPTION
**Pull request by pclouds**
This is another annoyance point for me when I keep having to paste the
same command over and over during the "edit, build, test" cycles (emacs
inferior scheme does not seem a good fit for this, but probably because
I still prefer shells outside of emacs).

This is the absolute minimum to load history from a file by setting
GAUCHE_HISTFILE to e.g. ~/.gosh_history and save the history at exit.

There are more we could do, like setting history size, support appending
to ~/.gosh_history ... Those can wait.

### CODE REVIEW

**Comment by shirok** [comment]
Cool.  But a couple of catches:

- When it saves the history, write to temporary file and rename, so that even if multiple gosh tries to write it or an error occurs during write, we can be sure that the history file isn't broken.  You may want to use `call-with-temporary-file` in `file.util`.

- Anything persistent needs to be prepared for data format change across releases.  Adding a header (e.g. `(gosh-history-version 1)`) and auto-converting or ignoring unsupported version may suffice.

**Comment by shirok** [comment]
It may also nice to catch errors while reading the history file and ignore it.  It would be confusing for novice users if gosh throws an error because of broken history file.

**Comment by pclouds** [comment]
The first two points are easy to fix. I think I've caught most errors while reading history, not sure if with-input-from-file can cause errors and needs to be caught too.

Not catching errors could be really bad actually. At least the few times I broke save-history, I was unable to exit gosh because the error was caught by repl (i guess) and exit was aborted. I had to `killall gosh` instead.

The last commit is unrelated to persistent history, but feels nice to have.

**Comment by shirok** [comment]
Looks good.  Thanks!

**Comment by shirok** [comment]
I made a few changes:

- Made persistent history enabled by default, even without environment variable.  By default, it's saved in `~/.gosh_history`.
- Changed environment variable name to `GAUCHE_HISTORY_FILE`.  We tend to use full spelling in other environment variables, so I followed it.
- To disable using history, set empty string to `GAUCHE_HISTORY_FILE`.
- If the process is suid/sgid-ed, we won't use history.

**Pull request merged**
