### PR TITLE
Refactor Makefile

### PR DESCRIPTION
**Pull request by qykth-git**
Use modern commands to simplify Makefile.

### CODE REVIEW

**Comment by okuoku** [comment]
Although it's almost universally available, realpath(1) is not POSIX i guess. (realpath(3) still definitely is though).

**Comment by shirok** [comment]
The reason that I use grep to filter out "{Entering|Leaving} directory" message instead of using -s was that there were cases that make -s fails, though I don't quire remember what it was.  You're right that it doesn't work if the message is i18n-ed.  I'll check it out.

**Comment by shirok** [comment]
I cherry-pick the last one.  I'd avoid using realpath(1) for now.  About 'make -s' I need to remember what was the issue.

**Comment by qykth-git** [comment]
`cd $top_builddir/ext; ${MAKE:=make} list-objects` in `src/list-ext-objects.sh` is not so good one.
Because it can't stop when `cd $top_builddir/ext` was faild. I recommend:
```sh
cd $top_builddir/ext && ${MAKE:=make} list-objects
```
or
```sh
${MAKE:=make} -C $top_builddir/ext list-objects
```

And, current `src/list-ext-objects.sh` is not works well that `top_builddir` held some weird values like `././//`.

GNU Make has special function "realpath" that resolves to absolute path name. But it has GNU-Make only.
```makefile
ABS_OBJECTS = $(realpath $(OBJECTS))
```

I revised my patches to use for another cherry-pick.

**Comment by shirok** [comment]
I addressed the issue of localized make messages; instead of removing unwanted messages, we pick necessary info, by adding characteristic strings to it.

I still want to avoid relying on realpath.  If you have fixes for remaining issues, I appreciate if you submit a new PR.

**Comment by qykth-git** [comment]
Thanks. it worked even in Japanese environment.

**Pull request closed without merging**
