### PR TITLE
Scoop manifest generator

### PR DESCRIPTION
**Pull request by qykth-git**
Add Scoop manifest generator.

See also #627 #539 .

### CODE REVIEW

**Comment by shirok** [comment]
Thanks!

**Comment by lassik** [comment]
@gykth-git What would be the next step in adding Gauche to Scoop's main repo - do you have prior experience submitting a package there?

**Comment by qykth-git** [comment]
@lassik 
I will add generated file to Scoop as next step.

**Comment by qykth-git** [comment]
@lassik 
Gauche manifest was now merged into upstream at https://github.com/ScoopInstaller/Main/pull/897 .

**Comment by lassik** [comment]
@qykth-git I tried it and it works. Thanks a lot for your efforts!

**Pull request merged**
