### PR TITLE
regexp: extend 'rxmatch' to search in a substring

### PR DESCRIPTION
**Pull request by pclouds**
This is needed by SRFI-115 which provides procedures like

    (regexp-search re str [start [end]]) => regexp-match-or-false

Simulating it by calling

    (substring str start end)

first and passing the substring to rxmatch is not enough because the
start/end offsets in the match objects will be relative to the substring
instead of the full string (chibi goes with the latter, the SRFI
mentions nothing about this).

The new start is now assigned to ctx->input to be the real beginning of
the search string. make_match() still works on the original string
object, so all offsets are relative to full string.

### CODE REVIEW

**Comment by shirok** [comment]
Wow this is a significant work.  Greatly appreciated.
The change of Scm_RegCompFromAST breaks the ABI compatibility so I'll tweak it a little after merge.
(making the new interface another name, and the next compatibility-breaking release (probably 1.0) we switch it.)

**Comment by shirok** [comment]
I added your copyright in srfi-115.scm and sre.scm (modified BSD).  Hope you don't mind.

**Comment by pclouds** [comment]
Eck.. I think I accidentally pushed more into this branch. Too late to change anything now :D

**Comment by pclouds** [comment]
> I added your copyright in srfi-115.scm and sre.scm (modified BSD). Hope you don't mind.

No problem. regexp-split and regexp-partition were actually copied from chibi btw (I would have mentioned this if it was a separate PR).

**Pull request merged**
