### PR TITLE
interactive.scm: delete outdated comment

### PR DESCRIPTION
**Pull request by pclouds**
It seems multibyte chars have been supported (likely done by Hamayama based on git history). Cursor movement works, deleting, inserting, cutting and pasting work (but I did not test adding text with an IM). Line wrapping seems fine too.

The screen height problem seems fixed too (also likely by Hamayama). When the expressions are longer than screen height, we only display the lines that contain the cursor (and fit in the terminal).

It flickers like hell though on those long expressions. But at least it displays correctly.

### CODE REVIEW

**Comment by shirok** [comment]
I agree.  It hasn't been updated.

It'll be nice to reduce screen flickering.  I'll track it in https://github.com/shirok/Gauche/issues/665

**Comment by pclouds** [comment]
Besides the flicker issue, is there anything else before we remove experimental status for the line editor?

**Comment by shirok** [comment]
The only thing is that I use the feature only sporadically--when I don't use gosh inside Emacs.  But if you use it all the time and feels it's ready for general use, I'll make it default.   Surely it'll be nice if we can turn this on by default in 1.0.

**Comment by pclouds** [comment]
It's been enabled for me in the last couple months and I often use gosh from command line more than emacs these days. Making it default may be too early though, there could be some weird terminal types that cause trouble.

We could adding a command line option to make it easier to enable (and maybe some similar mechanism to enable it from .gaucherc). And encourage people from using it in documents. Then after a release or two of no bug reports, we can consider enabling it by default (at least on safe terminal types).

I think we need to somehow document the key bindings too. Right now you just have to try and see. We could implement C-h b for that (I already want to implement completion, either bound to \<tab> or M-/ which also prints extra stuff besides the current prompt).

**Comment by shirok** [comment]
About terminal types: We determine supported terminals in whitelist, so if the terminal isn't known to work with, the feature won't be turned on. 

I planned to add command-line option to *suppress* line editing once we make line editing default; e.g. when the user suspect the feature is buggy and try to run gosh without it temporarily.  I feel environment variable is easy enough to put a sticky settings.   Currently, `.gaucherc` is not suitable, for when it is read the decision to use line-edit or not is already done.

The best course is to advertise the feature more in the document, while keeping it opt-in for a while.  The key assignment document is definitely desired, but online help may be good.  Oh but don't use `C-h`  -- it is the only default Emacs binding I always switch, since it conflicts backspace (for old timers like me, `C-h` *is* backspace).  Maybe I can enhance `,help` command.

**Comment by pclouds** [comment]
> The key assignment document is definitely desired, but online help may be good. Oh but don't use C-h

I see you've done most of the groundwork for this. So, use `C-x h` as the help key prefix? `C-x h m` shows the key map, `C-x h k <key sequence>` to display a specific key description?

And I'm thinking to add `C-x C-e` to edit the current buffer in an editor btw. It's from bash, quite convenient when an expr is getting out of hand...

**Comment by shirok** [comment]
Sounds good.  You want to give a shot?

**Comment by pclouds** [comment]
Nah you'll do it must faster :D

**Pull request merged**
