### PR TITLE
Convert "INSTALL" file to AsciiDoc format

### PR DESCRIPTION
**Pull request by qykth-git**
Convert plain text to AsciiDoc format.

* Add generated HTML file to ".tgz" distribution archive.
* Use [AsciiDoc](http://asciidoc.org/) or [AsciiDoctor](https://asciidoctor.org/) to make HTML output.

### CODE REVIEW

**Comment by shirok** [comment]
Using Asciidoc, the code blocks somehow disappear in html:
```
<h2 id="_quick_start">Quick Start</h2>
<div class="sectionbody">
<div class="listingblock">
<div class="content"></div></div>
<div class="paragraph"><p>Things will be installed under <code>/usr/local/bin....
```

I'm old school and still prefer the files you first read after untarring the archive being plain-text readable.  Multilingual adoc source can't serve as an easily-readable document---the `ifdef::JA[]` markups and another language parts are too much noise.

Is there a way to generate plain-text formatted document from adoc?

**Comment by qykth-git** [comment]
Use [a2x(1)](http://asciidoc.org/a2x.1.html) to convert from AsciiDoc to plain text file.

**Comment by shirok** [comment]
Hmm, in my environment, a2x replaces all Japanese characters to '?'.  (a2x seems to call w3m to render to text, so it may be w3m which needs proper setup.)

The rendered result of English text is nice, except that I prefer code blocks being indented.  But if we need lots of tweaks to get satisfying text rendering, it might not be worth it...

I've got a feeling that invoking the whole asciidoc toolchain seems overkill, given that our target format is plain text.   The whole point of adoc-tizing is to provide nice rendering in browsing github repo with browser, while having reasonably readable text format in the source.  The current INSTALL.adoc achieves the nice browser rendering, but source is not quite readable with all those if-directives.  So, the options I think feasible are:

- Have INSTALL.adoc and INSTALL.ja.adoc separately in the source tree.  This achieves both nice browsing and human-readable text.  Downside is that we have to maintain two versions separately.
- Have INSTALL.adoc as in the current way, and process it with our own filter program to produce English and Japanese versions of adoc files.  This also achieves both nice browsing and human-readable text.  Downside is that we have to write a new filter program.
- Just keep the original text version.

I think option 2 isn't that bad, for we only need to process #/^(ifdef|endif)::..\[\]/ and removing the preamble part.  I don't want to clutter doc/extract.scm, though; it's already messy.  We can add a separate routine in doc/extract.scm (instead of adding to the current filter procedure) and switch by a command-line arg.

**Comment by qykth-git** [comment]
I choose option 2, and update the pull request.

* Split document to each language ".adoc" file from one source file.
* Properly output Japanese text.
* Indent code block.

How about this one?

**Comment by shirok** [comment]
Nice sed work; didn't think it's that simple.  If we have INSTALL.{en|jp}.adoc in tarball I don't think we need text version, since adoc is readable enough.  But I can merge yours and tweak it later.  Thanks a lot.

**Pull request merged**
